[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
categories = ["cryptography", "algorithms"]
description = """The Paillier cryptosystem is a public key crytosystem based on composite degree residuosity classes.
Paillier ciphertexts are homorphic in that the can be added.
"""
documentation = "https://docs.rs/paillier-rs"
edition = "2018"
license = "Apache-2.0"
name = "libpaillier"
readme = "README.md"
repository = "https://github.com/mikelodder7/paillier-rs"
version = "0.4.0"

[features]
default = ["openssl"]
gmp = ["unknown_order/gmp"]
openssl = ["unknown_order/openssl"]
rust = ["unknown_order/rust"]
wasm = ["getrandom", "wasm-bindgen", "serde-wasm-bindgen"]

[dependencies]
digest = "0.9"
getrandom = { version = "0.2", features = ["js"], optional = true }
rand_core = { version = "0.6", default_features = false }
serde = { version = "1.0", features = ["serde_derive"] }
serde_bare = "0.5"
unknown_order = { version = "0.5.0", default-features = false }
wasm-bindgen = { version = "0.2", default-features = false, features = ["serde-serialize"], optional = true }
zeroize = { version = "1.4", features = ["zeroize_derive"] }
serde-wasm-bindgen = { version = "0.4", optional = true }

[dev-dependencies]
elliptic-curve = "0.9"
hex = "0.4"
k256 = { version = "0.9", features = ["arithmetic", "zeroize"] }
rand = "0.8"
multibase = "0.9"
sha2 = "0.9"
serde_json = "1.0"
unicase = "2.6"
